services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campus_api
    restart: unless-stopped

    command: >
      sh -c "/app/.venv/bin/alembic upgrade head &&
             /app/.venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000"

    ports:
      - "8000:8000"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

      REDIS_URL: redis://redis:6379/0

      GROQ_API_KEY: ${GROQ_API_KEY}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}

      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      DOCUMENT_UPLOAD_DIR: /app/data/documents
      DOCUMENT_EXTRACTED_DIR: /app/data/extracted
      MAX_UPLOAD_SIZE_MB: ${MAX_UPLOAD_SIZE_MB}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    volumes:
      - document_data:/app/data

  postgres:
    image: pgvector/pgvector:pg16
    container_name: campus_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: campus_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

volumes:
  postgres_data:
  document_data: