services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: campus_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: campus_knowledge
      POSTGRES_USER: campus_user
      POSTGRES_PASSWORD: campus_password

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: