"""add full text search vector

Revision ID: 5f5b05a70f77
Revises: 3f7da7579c99
Create Date: 2026-09-15 13:25:30.241980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f5b05a70f77'
down_revision: Union[str, Sequence[str], None] = '3f7da7579c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'search_vector')
    # ### end Alembic commands ###
