"""add chunk metadata

Revision ID: 756611425ed8
Revises: 1404ec654b24
Create Date: 2026-09-13 15:55:22.859746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756611425ed8'
down_revision: Union[str, Sequence[str], None] = '1404ec654b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('chunks', sa.Column('access_level', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_chunks_access_level'), 'chunks', ['access_level'], unique=False)
    op.create_index(op.f('ix_chunks_department'), 'chunks', ['department'], unique=False)
    op.create_index(op.f('ix_chunks_year'), 'chunks', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_year'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_department'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_access_level'), table_name='chunks')
    op.drop_column('chunks', 'access_level')
    op.drop_column('chunks', 'department')
    op.drop_column('chunks', 'year')
    # ### end Alembic commands ###
